---
title: "p8105_hw6_cg3112"
output: html_document
---

```{r}
library(tidyr)
library(plotly)
library(dplyr)
library(tidyverse)
library(modelr)
library(mgcv)
set.seed(1)
```


# Problem 1

```{r}
births <- read_csv("./birthweight.csv") %>%
  mutate(
   babysex = as.factor(babysex),
   frace = as.factor(frace),
   malform = as.factor(malform),
   mrace = as.factor(mrace)
  )

```

Checking for missing data:
```{r}
skimr::skim(births)
```
There does not appear to be any missing values.

Lets propose a model based on scientific knowledge of predictors of birth weight:

```{r}
weight <-
  lm(bwt ~ momage + delwt + smoken + wtgain, data = births) 

weighting <- weight %>% 
  broom::tidy() %>%
   knitr::kable(digits = 3)

weighting
```

We'll next add the residuals and predictions: 
```{r}
res_pred <- births %>%
   modelr::add_residuals( weight) %>%
   modelr::add_predictions( weight)

res_pred %>%
   ggplot(aes(x = pred, y = resid)) + geom_point()
```

In comparing our model to other models:

```{r}

#train <- sample_frac(births, size = .8)
#test <- sample_frac(births, size = .2)

cv_df = 
  crossv_mc(births, 100, test = 0.2) 

cv_df =
  cv_df %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

#model1 <- lm(bwt ~ blength + gaweeks, data = train)
#model2 <- lm(bwt ~ bhead * blength * babysex, data = train)

cv_df <- cv_df %>% 
   mutate(
    weight = map(train, ~lm(bwt ~ momage + delwt + smoken + wtgain, data=.x)),
    model1 = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    model2 = map(train, ~lm(bwt ~ bhead * blength * babysex, data=.x))) %>% 
  mutate(
     rmse_weight = map2_dbl(weight, test, ~rmse(model = .x, data = .y)),
     rmse_model1 = map2_dbl(model1, test, ~rmse(model = .x, data = .y)),
     rmse_model2 = map2_dbl(model2, test, ~rmse(model = .x, data = .y))
     )

cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()

#test %>% 
#   gather_predictions(weight, model1, model2) %>%
#   mutate (
#     model = fct_inorder(model)) %>%
#     ggplot(aes(x = pred , y = bwt)) + 
#     geom_point() + 
#     geom_line(aes(y = pred), color = "red") + 
#     facet_wrap(~model)
   
```
It appears that both of the other models do a better

```{r}
weight_r <- rmse(weight, births)
model1_r <- rmse(model1, births)
model2_r <- rmse(model2, births)

```

